// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Iavo7OmRuVyywk6t6sYsX_-P87ao4DA',
    appId: '1:625939332457:android:e3979b43af47ab0e0151f8',
    messagingSenderId: '625939332457',
    projectId: 'hr-policies-c321d',
    storageBucket: 'hr-policies-c321d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbljBRgBWkBPje4bRpivDocJWPa41aG74',
    appId: '1:625939332457:ios:1aa448899e3de10b0151f8',
    messagingSenderId: '625939332457',
    projectId: 'hr-policies-c321d',
    storageBucket: 'hr-policies-c321d.firebasestorage.app',
    iosBundleId: 'com.developers.todoapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhWnVwCwkuO81cUlb5GPWbwSv0O3qzbI',
    appId: '1:625939332457:web:e139f96fe31a38030151f8',
    messagingSenderId: '625939332457',
    projectId: 'hr-policies-c321d',
    authDomain: 'hr-policies-c321d.firebaseapp.com',
    storageBucket: 'hr-policies-c321d.firebasestorage.app',
    measurementId: 'G-G3RPM1RQQY',
  );

}